/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellSuppliersRouteImport } from './routes/_shell.suppliers'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSalesRouteImport } from './routes/_shell.sales'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellPurchasesRouteImport } from './routes/_shell.purchases'
import { Route as ShellProductsRouteImport } from './routes/_shell.products'
import { Route as ShellPosRouteImport } from './routes/_shell.pos'
import { Route as ShellOrdersRouteImport } from './routes/_shell.orders'
import { Route as ShellInventoryRouteImport } from './routes/_shell.inventory'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellCustomersRouteImport } from './routes/_shell.customers'
import { Route as ShellCategoriesRouteImport } from './routes/_shell.categories'
import { Route as ShellAuditLogsRouteImport } from './routes/_shell.audit-logs'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSuppliersRoute = ShellSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSalesRoute = ShellSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPurchasesRoute = ShellPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductsRoute = ShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPosRoute = ShellPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrdersRoute = ShellOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInventoryRoute = ShellInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCustomersRoute = ShellCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCategoriesRoute = ShellCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditLogsRoute = ShellAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit-logs': typeof ShellAuditLogsRoute
  '/categories': typeof ShellCategoriesRoute
  '/customers': typeof ShellCustomersRoute
  '/dashboard': typeof ShellDashboardRoute
  '/inventory': typeof ShellInventoryRoute
  '/orders': typeof ShellOrdersRoute
  '/pos': typeof ShellPosRoute
  '/products': typeof ShellProductsRoute
  '/purchases': typeof ShellPurchasesRoute
  '/reports': typeof ShellReportsRoute
  '/sales': typeof ShellSalesRoute
  '/settings': typeof ShellSettingsRoute
  '/suppliers': typeof ShellSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit-logs': typeof ShellAuditLogsRoute
  '/categories': typeof ShellCategoriesRoute
  '/customers': typeof ShellCustomersRoute
  '/dashboard': typeof ShellDashboardRoute
  '/inventory': typeof ShellInventoryRoute
  '/orders': typeof ShellOrdersRoute
  '/pos': typeof ShellPosRoute
  '/products': typeof ShellProductsRoute
  '/purchases': typeof ShellPurchasesRoute
  '/reports': typeof ShellReportsRoute
  '/sales': typeof ShellSalesRoute
  '/settings': typeof ShellSettingsRoute
  '/suppliers': typeof ShellSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_shell/audit-logs': typeof ShellAuditLogsRoute
  '/_shell/categories': typeof ShellCategoriesRoute
  '/_shell/customers': typeof ShellCustomersRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/inventory': typeof ShellInventoryRoute
  '/_shell/orders': typeof ShellOrdersRoute
  '/_shell/pos': typeof ShellPosRoute
  '/_shell/products': typeof ShellProductsRoute
  '/_shell/purchases': typeof ShellPurchasesRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/sales': typeof ShellSalesRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/suppliers': typeof ShellSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/shop'
    | '/sitemap.xml'
    | '/audit-logs'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/shop'
    | '/sitemap.xml'
    | '/audit-logs'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/auth'
    | '/shop'
    | '/sitemap.xml'
    | '/_shell/audit-logs'
    | '/_shell/categories'
    | '/_shell/customers'
    | '/_shell/dashboard'
    | '/_shell/inventory'
    | '/_shell/orders'
    | '/_shell/pos'
    | '/_shell/products'
    | '/_shell/purchases'
    | '/_shell/reports'
    | '/_shell/sales'
    | '/_shell/settings'
    | '/_shell/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/suppliers': {
      id: '/_shell/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof ShellSuppliersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sales': {
      id: '/_shell/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof ShellSalesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/purchases': {
      id: '/_shell/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof ShellPurchasesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/products': {
      id: '/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShellProductsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pos': {
      id: '/_shell/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof ShellPosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders': {
      id: '/_shell/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShellOrdersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inventory': {
      id: '/_shell/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ShellInventoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/customers': {
      id: '/_shell/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ShellCustomersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/categories': {
      id: '/_shell/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof ShellCategoriesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit-logs': {
      id: '/_shell/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof ShellAuditLogsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAuditLogsRoute: typeof ShellAuditLogsRoute
  ShellCategoriesRoute: typeof ShellCategoriesRoute
  ShellCustomersRoute: typeof ShellCustomersRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellInventoryRoute: typeof ShellInventoryRoute
  ShellOrdersRoute: typeof ShellOrdersRoute
  ShellPosRoute: typeof ShellPosRoute
  ShellProductsRoute: typeof ShellProductsRoute
  ShellPurchasesRoute: typeof ShellPurchasesRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSalesRoute: typeof ShellSalesRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSuppliersRoute: typeof ShellSuppliersRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAuditLogsRoute: ShellAuditLogsRoute,
  ShellCategoriesRoute: ShellCategoriesRoute,
  ShellCustomersRoute: ShellCustomersRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellInventoryRoute: ShellInventoryRoute,
  ShellOrdersRoute: ShellOrdersRoute,
  ShellPosRoute: ShellPosRoute,
  ShellProductsRoute: ShellProductsRoute,
  ShellPurchasesRoute: ShellPurchasesRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSalesRoute: ShellSalesRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSuppliersRoute: ShellSuppliersRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
